import type { Reflection } from "./index";

export const reflectionsTr: Reflection[] = [
  // ── Sabah ──────────────────────────────────────────────
  { id: "m01", text: "Bugün en derin değerlerini onurlandıran hangi niyeti taşıyabilirsin?", category: "morning" },
  { id: "m02", text: "Bu sabah ilk ortaya çıkan duyguyu fark et. Senden ne istiyor olabilir?", category: "morning" },
  { id: "m03", text: "Gün başlamadan önce kendine gösterebileceğin küçük bir nezaket eylemini düşün.", category: "morning" },
  { id: "m04", text: "Bugün kendinin hangi yönünü öne çıkarmaya hazırsın?", category: "morning" },
  { id: "m05", text: "Dünya akışına kapılmadan önce bir nefes al ve sor: şu an en çok ne önemli?", category: "morning" },
  { id: "m06", text: "Bugüne ilk kez deneyimleyen birinin merakıyla nasıl yaklaşabilirsin?", category: "morning" },
  { id: "m07", text: "Bu günü kendi temponla geçirmek nasıl görünürdü?", category: "morning" },
  { id: "m08", text: "Ayakların yere değmeden önce minnettar olduğun bir şeyi isimlendir.", category: "morning" },
  { id: "m09", text: "Bugün hangi niteliği somutlaştırmak istiyorsun — sabır, cesaret, nezaket ya da bambaşka bir şey?", category: "morning" },
  { id: "m10", text: "Bugünkü ilk etkileşimine taşımak istediğin enerjiyi düşün.", category: "morning" },
  { id: "m11", text: "Bu sabah bedeninin neye ihtiyacı var? Planlamadan önce dinle.", category: "morning" },
  { id: "m12", text: "Bugünün en iyi halini hayal et. Bu vizyona doğru atabileceğin bir adım ne olabilir?", category: "morning" },
  { id: "m13", text: "Günün ivmesi seni yakalamadan önce nasıl bir durağanlık anı yaratabilirsin?", category: "morning" },
  { id: "m14", text: "Bugüne taze gözlerle bakabilmek için dünden neyi bırakmayı seçiyorsun?", category: "morning" },
  { id: "m15", text: "Düşüncelerinin ilk nereye gittiğini fark et. O yön, neyin ilgi istediğine dair bir ipucu taşıyabilir.", category: "morning" },
  { id: "m16", text: "Bugün iyilik halini destekleyen hangi kişisel sınırı koruyabilirsin?", category: "morning" },
  { id: "m17", text: "Bugüne bir yapılacaklar listesiyle değil, bir olunacaklar listesiyle başlamayı düşün.", category: "morning" },

  // ── Akşam ──────────────────────────────────────────────
  { id: "e01", text: "Bugünden en çok gurur duyduğun an hangisiydi, küçük bile olsa?", category: "evening" },
  { id: "e02", text: "Bugün yaptığın bir sohbet üzerine düşün. Onun aracılığıyla kendin hakkında ne öğrendin?", category: "evening" },
  { id: "e03", text: "Bugün kendini ne için affedebilirsin? O yükün uykudan önce erimesine izin ver.", category: "evening" },
  { id: "e04", text: "Günden geriye kalan duyguları fark et. Her birini yargılamadan kabul et.", category: "evening" },
  { id: "e05", text: "Bugün seni ne zorladı ve nasıl karşılık verdin? Yanlış cevap yok.", category: "evening" },
  { id: "e06", text: "Bu günden beklenmedik bir güzellik ya da bağlantı anını hatırla.", category: "evening" },
  { id: "e07", text: "Bugün ihtiyaçların hakkında daha önce fark etmemiş olabileceğin ne öğretti?", category: "evening" },
  { id: "e08", text: "Gün kapanırken düşün: doluluktan mı yoksa tükenmişlikten mi verdin?", category: "evening" },
  { id: "e09", text: "Bu gece hangi düşünceyi ya da kaygıyı bırakabilirsin, sabaha kadar bekleyebileceğine güvenerek?", category: "evening" },
  { id: "e10", text: "Planladığın ile gerçekten olan arasındaki boşluk üzerine düşün. O aralıkta ne yaşıyor?", category: "evening" },
  { id: "e11", text: "Bugün sana kim ya da ne rahatlık verdi? Dinlenmeye doğru süzülürken o görüntüyü tut.", category: "evening" },
  { id: "e12", text: "Bugünden yarım kalan hangi düşünce, uyumadan önce bir anlık ilgini hak ediyor?", category: "evening" },
  { id: "e13", text: "Bugünkü enerji ritmini düşün. Ne zaman kendini en canlı hissettin?", category: "evening" },
  { id: "e14", text: "Bugün neye direndin? Bazen direnç, incelemeye değer bir işaret taşır.", category: "evening" },
  { id: "e15", text: "Bu gece bir eşik olsun. Neyi yanında taşıyorsun, ne geride kalıyor?", category: "evening" },
  { id: "e16", text: "Büyük ya da küçük, bugün yolunda giden üç şey söyle.", category: "evening" },
  { id: "e17", text: "Tam senin yaşadığın günü yaşamış bir arkadaşına ne söylerdin?", category: "evening" },

  // ── Gelişim ───────────────────────────────────────────────
  { id: "g01", text: "Hayatında daha net fark etmeye başladığın hangi örüntü var?", category: "growth", relatedPlanet: "saturn" },
  { id: "g02", text: "Bir yıl önceki sen ile şimdiki sen arasındaki farkı düşün. Ne değişti?", category: "growth", relatedPlanet: "jupiter" },
  { id: "g03", text: "Bir sonraki bölümünün anahtarını taşıyabilecek hangi korkudan kaçınıyordun?", category: "growth", relatedPlanet: "pluto" },
  { id: "g04", text: "Gelişim genellikle rahatsızlığın içinde gizlenir. Hangi rahatsız edici gerçekle yüzleşmeye hazırsın?", category: "growth", relatedPlanet: "saturn" },
  { id: "g05", text: "Kendinle ilgili sessizce süresi dolmuş hangi inanç var? Onu bırakmayı düşün.", category: "growth", relatedPlanet: "pluto" },
  { id: "g06", text: "Nerede takılı hissettiğini fark et. O durağanlık, daha derine bakmaya bir davet olabilir.", category: "growth", relatedElement: "water" },
  { id: "g07", text: "Şu anda hangi beceriyi ya da niteliği geliştiriyorsun, ilerleme görünmez hissettirse bile?", category: "growth", relatedPlanet: "saturn" },
  { id: "g08", text: "Sonradan öğretmene dönüşen bir hatayı düşün. Sana ne sundu?", category: "growth", relatedPlanet: "jupiter" },
  { id: "g09", text: "Kimliğinin hangi kısmını aşıyorsun? Onu onurlandır ve sonra evrilmesine izin ver.", category: "growth", relatedPlanet: "uranus" },
  { id: "g10", text: "Hayatının neresinde kendini küçük tutuyorsun? Genişleme nasıl görünürdü?", category: "growth", relatedPlanet: "jupiter" },
  { id: "g11", text: "Kendine tamamen güvensen ne denemeye kalkışırdın?", category: "growth", relatedElement: "fire" },
  { id: "g12", text: "Yakın zamanda koyduğun bir sınır üzerine düşün. Gelişimine nasıl hizmet etti?", category: "growth", relatedPlanet: "saturn" },
  { id: "g13", text: "Kim olduğun ile kim olmakta olduğun arasındaki alanı keşfetmeyi düşün.", category: "growth", relatedPlanet: "neptune" },
  { id: "g14", text: "Hangi ders sana tekrar tekrar geri dönüyor? Belki de tam olarak alınmaya hazırdır.", category: "growth", relatedPlanet: "saturn" },
  { id: "g15", text: "Gelişimin her zaman ileri bir hareket olmadığını fark edebilirsin — bazen derinleşmektir.", category: "growth", relatedElement: "earth" },
  { id: "g16", text: "Kendinle hangi konuşmayı erteliyordun?", category: "growth", relatedPlanet: "mercury" },
  { id: "g17", text: "Son zamanlarda kendini şaşırtma biçimlerini düşün. Ne ortaya çıkarıyorlar?", category: "growth", relatedPlanet: "uranus" },

  // ── İlişki ─────────────────────────────────────────
  { id: "r01", text: "En yakın ilişkinde nazikçe ifade edilmeyi hak eden hangi söylenmemiş ihtiyaç var?", category: "relationship", relatedPlanet: "venus" },
  { id: "r02", text: "Sevgiyi nasıl gösterdiğini düşün. Almak istediğin şekille aynı mı?", category: "relationship", relatedPlanet: "venus" },
  { id: "r03", text: "Son zamanlarda değişen bir ilişki üzerine düşün. Bu değişimden ne öğreniyorsun?", category: "relationship", relatedPlanet: "venus" },
  { id: "r04", text: "Hayatında güven şu an nasıl görünüyor? Nerede güçlü, nerede bakıma ihtiyacı var?", category: "relationship", relatedSign: "scorpio" },
  { id: "r05", text: "Sana enerji veren insanları fark et. Hangi nitelikleri sana yansıtıyorlar?", category: "relationship", relatedElement: "fire" },
  { id: "r06", text: "İlişkilerinde genellikle hangi rolü üstleniyorsun? Seçtiğin bir rol mü, yoksa içine düştüğün mü?", category: "relationship", relatedPlanet: "moon" },
  { id: "r07", text: "Kendin için isteyeceğin aynı merhameti bir başkasına da uzatmayı düşün.", category: "relationship", relatedSign: "pisces" },
  { id: "r08", text: "Bir ilişkide hangi sınırın güçlendirilmesi gerekiyor — bir duvar olarak değil, bir özen biçimi olarak?", category: "relationship", relatedSign: "capricorn" },
  { id: "r09", text: "Bu haftadan gerçek bir bağlantı anını düşün. Onu mümkün kılan neydi?", category: "relationship", relatedPlanet: "venus" },
  { id: "r10", text: "Hayatında kime içten bir minnettarlık anı borçlusun?", category: "relationship", relatedSign: "taurus" },
  { id: "r11", text: "Ne zaman almaktan kaçınmak için verdiğini fark et. Bu örüntü neyi koruyor olabilir?", category: "relationship", relatedPlanet: "moon" },
  { id: "r12", text: "Sağlıklı çatışma senin için nasıl görünüyor? Bu soruyu yargısızca keşfetmeyi düşün.", category: "relationship", relatedSign: "libra" },
  { id: "r13", text: "Kendinle olan ilişkin üzerine düşün. Diğer tüm bağlantılarını şekillendiren odur.", category: "relationship", relatedPlanet: "moon" },
  { id: "r14", text: "Gerçekten dinlemek — yanıt vermek için değil, anlamak için — ne anlama gelirdi?", category: "relationship", relatedPlanet: "mercury" },
  { id: "r15", text: "Birine ihtiyaç duymak ile birini seçmek arasındaki farkı düşün. İkisi de geçerlidir.", category: "relationship", relatedPlanet: "venus" },
  { id: "r16", text: "Sana sevgi hakkında en çok kim öğretti ve ders neydi?", category: "relationship", relatedPlanet: "venus" },

  // ── Kariyer ───────────────────────────────────────────────
  { id: "c01", text: "İşinin hangi kısmı gerçek benliğinle en çok örtüşüyor?", category: "career", relatedPlanet: "sun" },
  { id: "c02", text: "Korkunun yönlendirdiği hırs ile amacın yönlendirdiği hırs arasındaki farkı düşün.", category: "career", relatedPlanet: "mars" },
  { id: "c03", text: "Başkalarının sürekli fark ettiği ama senin küçümsediğin hangi becerin var?", category: "career", relatedPlanet: "mercury" },
  { id: "c04", text: "Başarının senin için ne anlama geldiğini düşün — dünyanın tanımını değil, seninkini.", category: "career", relatedSign: "capricorn" },
  { id: "c05", text: "Kariyerinde başka birinin yazdığı bir senaryoyu nerede takip ediyorsun? Onu gözden geçirmeyi düşün.", category: "career", relatedPlanet: "saturn" },
  { id: "c06", text: "İşin değerlerinin tam bir ifadesi olsaydı nasıl görünürdü?", category: "career", relatedPlanet: "sun" },
  { id: "c07", text: "Mükemmeliyetçiliğin seni nerede yavaşlattığını fark et. İlerleme çoğu zaman ciladan daha önemlidir.", category: "career", relatedSign: "virgo" },
  { id: "c08", text: "Tartıp durduğun hangi mesleki risk var? Onu alarak ne kazanabileceğini düşün.", category: "career", relatedPlanet: "jupiter" },
  { id: "c09", text: "Seni şekillendiren liderler ve mentorlar üzerine düşün. Onların hangi nitelikleri artık senin?", category: "career", relatedPlanet: "saturn" },
  { id: "c10", text: "Dinlenmenin üretkenliğin zıttı olmadığını fark edebilirsin — onun temelidir.", category: "career", relatedPlanet: "moon" },
  { id: "c11", text: "Kimse izlemeseydi ne inşa ederdin?", category: "career", relatedPlanet: "sun" },
  { id: "c12", text: "Günlük çalışmanla sessizce yarattığın mirası düşün.", category: "career", relatedSign: "capricorn" },
  { id: "c13", text: "Profesyonel hayatında emek ve rahatlık arasındaki denge nasıl görünüyor?", category: "career", relatedSign: "libra" },
  { id: "c14", text: "Seni daha iyi bir şeye yönlendiren bir aksilik üzerine düşün.", category: "career", relatedPlanet: "saturn" },
  { id: "c15", text: "İşinde hangi iş birliği enerjisini arıyorsun ve onu nasıl davet edebilirsin?", category: "career", relatedElement: "air" },
  { id: "c16", text: "Şu anki temponun sürdürülebilir olup olmadığını düşün. Beden ısrar etmeden önce ayarla.", category: "career", relatedSign: "taurus" },

  // ── Ruhani ────────────────────────────────────────────
  { id: "s01", text: "İç sessizliğin, durmaya yetecek kadar zaman ayırdığında nasıl duyuluyor?", category: "spiritual", relatedPlanet: "neptune" },
  { id: "s02", text: "Etrafındaki doğadaki döngüleri düşün. Hangisi kendi iç mevsimini yansıtıyor?", category: "spiritual", relatedPlanet: "moon" },
  { id: "s03", text: "Hayat dengesiz hissettirdiğinde seni çıpalayan hangi kutsal pratik var — ne kadar küçük olursa olsun?", category: "spiritual", relatedPlanet: "neptune" },
  { id: "s04", text: "Zamanın eriyip gittiği anları fark et. O anlarda ne yapıyorsun?", category: "spiritual", relatedPlanet: "neptune" },
  { id: "s05", text: "İç dünyan ile etrafındaki dünya arasındaki bağlantı üzerine düşün.", category: "spiritual", relatedElement: "water" },
  { id: "s06", text: "Ruhunun sorduğu ama zihninin yanıtlamaya çalıştığı hangi soru var?", category: "spiritual", relatedPlanet: "neptune" },
  { id: "s07", text: "Hem dalga hem okyanus olduğun fikrini düşün. Bu nasıl hissettiriyor?", category: "spiritual", relatedSign: "pisces" },
  { id: "s08", text: "Teslim olmak senin için ne anlama geliyor? Vazgeçmek değil, kontrol ihtiyacını bırakmak.", category: "spiritual", relatedPlanet: "neptune" },
  { id: "s09", text: "Sezgi ile aşırı düşünme arasındaki ince çizgiyi fark et. Bugün neredesin?", category: "spiritual", relatedPlanet: "moon" },
  { id: "s10", text: "Gerçek ya da hayal ürünü hangi ata, öğretmen ya da rehberin yanında yürüdüğünü hissediyorsun?", category: "spiritual", relatedPlanet: "pluto" },
  { id: "s11", text: "Son zamanlarda yaşadığın bir eşzamanlılık üzerine düşün. Ona hangi anlamı yüklüyorsun?", category: "spiritual", relatedPlanet: "uranus" },
  { id: "s12", text: "Nefeslerinin arasındaki sessizliği keşfetmeyi düşün. Orada bir şey yaşıyor.", category: "spiritual", relatedPlanet: "neptune" },
  { id: "s13", text: "Doğal dünyanın hangi parçası sana kendi özünü hatırlatıyor?", category: "spiritual", relatedElement: "earth" },
  { id: "s14", text: "Bu arketip seni, yolunu şekillendiren görünmez güçlere güvenmeye davet ediyor.", category: "spiritual", relatedPlanet: "pluto" },
  { id: "s15", text: "Hangi ritüel — sabah çayı, yürüyüş, günlük tutma — seni daha büyük bir şeye bağlıyor?", category: "spiritual", relatedPlanet: "moon" },
  { id: "s16", text: "İnanç ile şüphenin sende bir arada var olduğu yeri fark et. İkisi de yolculukta geçerli yol arkadaşlarıdır.", category: "spiritual", relatedSign: "sagittarius" },
  { id: "s17", text: "Evrenin gözlemlediğin bir şey değil, içinde yer aldığın bir şey olduğunu düşün.", category: "spiritual", relatedPlanet: "neptune" },
];
