import type { Affirmation } from "./index";

export const affirmationsTr: Affirmation[] = [
  // ── Öz Değer ───────────────────────────────────────────
  { id: "sw01", text: "Bu anda, tam olduğum gibi yeteriyim.", theme: "self-worth" },
  { id: "sw02", text: "Değerim üretkenliğimle ya da çıktılarımla ölçülmez.", theme: "self-worth", relatedSign: "virgo" },
  { id: "sw03", text: "Beni ben yapan eşsiz nitelikleri onurlandırıyorum.", theme: "self-worth", relatedSign: "aquarius" },
  { id: "sw04", text: "Başkalarına özgürce verdiğim aynı merhameti hak ediyorum.", theme: "self-worth", relatedSign: "pisces" },
  { id: "sw05", text: "Sesim önemli ve onu kullanmak konusunda kendime güveniyorum.", theme: "self-worth", relatedSign: "leo" },
  { id: "sw06", text: "Kendi değerimi bilmek için dışarıdan onay alma ihtiyacını bırakıyorum.", theme: "self-worth", relatedSign: "taurus" },
  { id: "sw07", text: "Küçülmemi gerektirmeyen bir sevgiyi hak ediyorum.", theme: "self-worth", relatedSign: "leo" },
  { id: "sw08", text: "Kusurlarım derinliğimin bir parçası, değerimin azalması değil.", theme: "self-worth", relatedSign: "virgo" },
  { id: "sw09", text: "Yolculuğumda tam olarak olmam gereken yerde olduğuma güveniyorum.", theme: "self-worth" },
  { id: "sw10", text: "Yer kaplamaya, görülmeye ve duyulmaya hakkım var.", theme: "self-worth", relatedSign: "aries" },
  { id: "sw11", text: "Şüphe ziyarete gelse bile kendi kapasiteme inanmayı seçiyorum.", theme: "self-worth", relatedSign: "capricorn" },
  { id: "sw12", text: "Hiçbir koşulun azaltamayacağı doğuştan gelen bir değer taşıyorum.", theme: "self-worth" },
  { id: "sw13", text: "Hassasiyetim bir güç, düzeltilmesi gereken bir kusur değil.", theme: "self-worth", relatedSign: "cancer" },

  // ── Gelişim ───────────────────────────────────────────────
  { id: "gr01", text: "Karşılaştığım her zorluk beni daha dayanıklı birine dönüştürüyor.", theme: "growth", relatedSign: "capricorn" },
  { id: "gr02", text: "Biçimi beni şaşırtsa bile dönüşümü karşılıyorum.", theme: "growth", relatedSign: "scorpio" },
  { id: "gr03", text: "Geride değilim. Kendi zaman çizelgemdeyim.", theme: "growth", relatedSign: "taurus" },
  { id: "gr04", text: "Hem kim olduğuma hem de kim olmakta olduğuma alan açmayı öğreniyorum.", theme: "growth" },
  { id: "gr05", text: "Hatalar başarısızlık değildir — daha derinden anlamaya davetlerdir.", theme: "growth", relatedSign: "sagittarius" },
  { id: "gr06", text: "Öz benliğimi terk etmeden evrilme kapasitesine sahibim.", theme: "growth", relatedSign: "scorpio" },
  { id: "gr07", text: "Yol belirsiz olsa bile oluş sürecine güveniyorum.", theme: "growth", relatedSign: "pisces" },
  { id: "gr08", text: "Artık bana hizmet etmeyen alanları aşmak için kendime izin veriyorum.", theme: "growth", relatedSign: "sagittarius" },
  { id: "gr09", text: "Gelişimim acı çekmeyi gerektirmez — neşeyle de gelebilir.", theme: "growth", relatedSign: "jupiter" },
  { id: "gr10", text: "Öğrenirken, öğrendiklerimi çözerken ve tekrar öğrenirken kendime karşı sabırlıyım.", theme: "growth", relatedSign: "virgo" },
  { id: "gr11", text: "Hayatımın her mevsimi kendi bilgeliğini taşır. Dinliyorum.", theme: "growth" },
  { id: "gr12", text: "Bilinmeyeni, genişlemem için verimli bir zemin olarak kucaklıyorum.", theme: "growth", relatedSign: "aquarius" },
  { id: "gr13", text: "Dünkü ben, beni buraya getirdi. O yolculuğu onurlandırıyorum.", theme: "growth" },

  // ── İlişkiler ────────────────────────────────────────
  { id: "re01", text: "Özgünlüğümü onurlandıran ilişkileri hayatıma çekiyorum.", theme: "relationships", relatedSign: "libra" },
  { id: "re02", text: "İhtiyaçlarımı netlik ve merhametle ifade ediyorum.", theme: "relationships", relatedSign: "gemini" },
  { id: "re03", text: "İstikrarlı, mevcut ve nazik bir sevgiyi hak ediyorum.", theme: "relationships", relatedSign: "taurus" },
  { id: "re04", text: "Benden kendime ihanet etmemi isteyen ilişkileri bırakıyorum.", theme: "relationships", relatedSign: "scorpio" },
  { id: "re05", text: "Bağlantıya tüm benliğimle giriyorum, bunun yeterli olduğuna güvenerek.", theme: "relationships", relatedSign: "leo" },
  { id: "re06", text: "Sağlıklı sınırlar bir sevgi ifadesidir — hem kendim hem de başkaları için.", theme: "relationships", relatedSign: "capricorn" },
  { id: "re07", text: "Derinden dinliyorum ve bunu yaparak gerçek yakınlık için alan yaratıyorum.", theme: "relationships", relatedSign: "cancer" },
  { id: "re08", text: "Sürtüşme anlarında bile başkalarındaki insanlığı görmeyi seçiyorum.", theme: "relationships", relatedSign: "pisces" },
  { id: "re09", text: "Verdiğim sevgi, beklemediğim biçimlerde bana geri dönüyor.", theme: "relationships", relatedSign: "libra" },
  { id: "re10", text: "Karşılıklı saygı ve samimi ilgiye dayanan bağlar kuruyorum.", theme: "relationships" },
  { id: "re11", text: "Kırılganlığın güvenle karşılandığı ortaklıkları hak ediyorum.", theme: "relationships", relatedSign: "cancer" },
  { id: "re12", text: "İlişkilerimin mevsimlerini onurlandırıyorum — yakınlık ve mesafenin ikisi de bir amaca hizmet eder.", theme: "relationships" },

  // ── Cesaret ──────────────────────────────────────────
  { id: "co01", text: "Zor olanla yüzleşecek güce ve yardım isteyecek bilgeliğe sahibim.", theme: "courage", relatedSign: "aries" },
  { id: "co02", text: "Korku bir dur işareti değil — bir bilgidir. İçinden geçmeyi seçiyorum.", theme: "courage", relatedSign: "scorpio" },
  { id: "co03", text: "Dünya gürültülü olsa bile içgüdülerime güveniyorum.", theme: "courage", relatedSign: "aries" },
  { id: "co04", text: "Gerçeğimi söylemek her gün pratik ettiğim bir cesaret eylemidir.", theme: "courage", relatedSign: "leo" },
  { id: "co05", text: "Kaç kez gerektirirse gereksin yeniden başlayacak kadar cesaretliyim.", theme: "courage", relatedSign: "aries" },
  { id: "co06", text: "Bilinmeyenle pervasızlıkla değil, sağlam bir kararlılıkla yüzleşiyorum.", theme: "courage", relatedSign: "capricorn" },
  { id: "co07", text: "Uymak daha kolay olsa bile kim olduğumda sağlam duruyorum.", theme: "courage", relatedSign: "aquarius" },
  { id: "co08", text: "Her onay yerine özgünlüğü seçtiğimde cesaretim büyüyor.", theme: "courage", relatedSign: "leo" },
  { id: "co09", text: "Beni korkutan şey tanımlamaz — nasıl karşılık verdiğim tanımlar.", theme: "courage" },
  { id: "co10", text: "Hazır hissetmeden önce ilk adımı atmak için kendime izin veriyorum.", theme: "courage", relatedSign: "aries" },
  { id: "co11", text: "İçimdeki ateş, dışarıdaki herhangi bir gölgeden daha parlaktır.", theme: "courage", relatedSign: "sagittarius" },
  { id: "co12", text: "İçimde beni buraya kadar taşımış sarsılmaz bir dayanıklılık var.", theme: "courage", relatedSign: "scorpio" },
  { id: "co13", text: "Kaçınma yerine eylemi, kafa karışıklığı yerine netliği seçiyorum.", theme: "courage", relatedSign: "aries" },

  // ── Huzur ────────────────────────────────────────────
  { id: "pe01", text: "Kontrol edemediğim şeyleri bırakıyor ve bu anın içinde huzur buluyorum.", theme: "peace", relatedSign: "pisces" },
  { id: "pe02", text: "Durağanlık boşluk değildir — fark edilmeyi bekleyen doluluktur.", theme: "peace", relatedSign: "taurus" },
  { id: "pe03", text: "Kendime suçluluk duymadan dinlenme ve özür dilemeden durma izni veriyorum.", theme: "peace", relatedSign: "cancer" },
  { id: "pe04", text: "İç huzurum, her an geri dönebileceğim bir sığınaktır.", theme: "peace" },
  { id: "pe05", text: "Ne getirirse getirsin bu güne eşit bir ruh haliyle yaklaşmayı seçiyorum.", theme: "peace", relatedSign: "libra" },
  { id: "pe06", text: "Kendi oluşumun hızıyla barışığım.", theme: "peace", relatedSign: "taurus" },
  { id: "pe07", text: "Gerginliği veriyorum, kabulü alıyorum.", theme: "peace" },
  { id: "pe08", text: "Bugün her şeyi çözmem gerekmiyor. Bazı şeyler kendi zamanında açılır.", theme: "peace", relatedSign: "pisces" },
  { id: "pe09", text: "Uyum içimde başlar ve onu nezaketle besliyorum.", theme: "peace", relatedSign: "libra" },
  { id: "pe10", text: "Sessizliğe alan açıyorum, onun kendi bilgeliğini taşıdığını bilerek.", theme: "peace" },
  { id: "pe11", text: "Beklentilerimin keskin köşelerini yumuşatıyor ve olanda huzur buluyorum.", theme: "peace", relatedSign: "pisces" },
  { id: "pe12", text: "Huzurum koşullara bağlı değildir — yaptığım bir seçimdir.", theme: "peace", relatedSign: "libra" },
  { id: "pe13", text: "Bir fısıltıya yavaşlasa bile hayatımın ritmine güveniyorum.", theme: "peace", relatedSign: "cancer" },

  // ── Bilgelik ───────────────────────────────────────────
  { id: "wi01", text: "Düşüncelerimin altında yaşayan derin bilgiye güveniyorum.", theme: "wisdom", relatedSign: "scorpio" },
  { id: "wi02", text: "Her deneyim bir öğretmen oldu ve aldığım dersleri onurlandırıyorum.", theme: "wisdom", relatedSign: "sagittarius" },
  { id: "wi03", text: "Karmaşıklığı basitleştirmeye acele etmeden taşıyorum.", theme: "wisdom", relatedSign: "gemini" },
  { id: "wi04", text: "Gerçek bilgelik, ne zaman konuşulacağını ve ne zaman dinleneceğini bilmeyi içerir.", theme: "wisdom", relatedSign: "virgo" },
  { id: "wi05", text: "Kesinlik değil, anlayış arıyorum. Sorular da cevaplar kadar önemlidir.", theme: "wisdom", relatedSign: "sagittarius" },
  { id: "wi06", text: "Hayatıma her şeyin bir anlam taşıdığı bakış açısıyla yaklaşıyorum.", theme: "wisdom" },
  { id: "wi07", text: "Geçmişten öğreniyorum ama onun tutsağı olmuyorum.", theme: "wisdom", relatedSign: "capricorn" },
  { id: "wi08", text: "Sezgim, onurlandırmayı seçtiğim bir içgörü kaynağıdır.", theme: "wisdom", relatedSign: "cancer" },
  { id: "wi09", text: "İlerlemek için her şeyi bilmem gerekmiyor, netlikle yol alabilirim.", theme: "wisdom", relatedSign: "sagittarius" },
  { id: "wi10", text: "Hızdan çok derinliğe, dikkat dağınıklığından çok mevcudiyete değer veriyorum.", theme: "wisdom", relatedSign: "scorpio" },
  { id: "wi11", text: "Hayatımın her bölümü, şimdi üzerinde durduğum bir anlayış temeli inşa etti.", theme: "wisdom" },
  { id: "wi12", text: "Henüz anlamadığım şeylere karşı meraklı kalıyorum. Merak, bilgeliğin bir biçimidir.", theme: "wisdom", relatedSign: "gemini" },

  // ── Bolluk ────────────────────────────────────────────
  { id: "ab01", text: "Hayatın sunduğu bütünlüğü almaya açığım.", theme: "abundance", relatedSign: "taurus" },
  { id: "ab02", text: "Yeterince var — yeterince zaman, yeterince sevgi, yeterince fırsat.", theme: "abundance", relatedSign: "sagittarius" },
  { id: "ab03", text: "Kıtlık düşüncesini bırakıyor ve beslenme akışını karşılıyorum.", theme: "abundance", relatedSign: "taurus" },
  { id: "ab04", text: "Hayatım maddi ölçülerin ötesinde zengindir.", theme: "abundance" },
  { id: "ab05", text: "Günlük hayatımda zaten var olan bolluğu fark ediyor ve kutluyorum.", theme: "abundance", relatedSign: "taurus" },
  { id: "ab06", text: "Cömertlik ve almak aynı döngünün iki yüzüdür. İkisini de onurlandırıyorum.", theme: "abundance", relatedSign: "leo" },
  { id: "ab07", text: "En özgün halimle ortaya çıkarak fırsatları çekiyorum.", theme: "abundance", relatedSign: "leo" },
  { id: "ab08", text: "Bana ait olanın çoktan yolda olduğuna güveniyorum.", theme: "abundance", relatedSign: "pisces" },
  { id: "ab09", text: "Zaten elimde olanı takdir ettiğimde refah duygusu büyüyor.", theme: "abundance", relatedSign: "taurus" },
  { id: "ab10", text: "Sahip olduklarımı açık bir yürekle paylaşarak bolluğu besliyorum.", theme: "abundance", relatedSign: "sagittarius" },
  { id: "ab11", text: "Kolaylığa, neşeye ve gerçek arzularımın gerçekleşmesine layığım.", theme: "abundance" },
  { id: "ab12", text: "Her gün fark ettiğimden fazlasını sunuyor. Açıkça görmeyi seçiyorum.", theme: "abundance" },

  // ── İyileşme ──────────────────────────────────────────
  { id: "he01", text: "Karşılaştırma yapmadan kendi hızımda iyileşmek için kendime izin veriyorum.", theme: "healing", relatedSign: "cancer" },
  { id: "he02", text: "Yaralarım kimliğim değil — hikayemin bir parçası, bütünü değil.", theme: "healing", relatedSign: "scorpio" },
  { id: "he03", text: "Sevdiğim birine göstereceğim aynı şefkatle kendimi beslemeyi seçiyorum.", theme: "healing", relatedSign: "cancer" },
  { id: "he04", text: "İyileşme bir varış noktası değildir. Her gün onurlandırdığım bir pratiktir.", theme: "healing" },
  { id: "he05", text: "Bu acıyı tek başıma taşımam gerektiği inancını bırakıyorum.", theme: "healing", relatedSign: "pisces" },
  { id: "he06", text: "Bedenim bilgelik taşıyor. Onu sabır ve saygıyla dinliyorum.", theme: "healing", relatedSign: "virgo" },
  { id: "he07", text: "Artık en yüksek iyiliğime hizmet etmeyen eski örüntüleri nazikçe çözüyorum.", theme: "healing", relatedSign: "scorpio" },
  { id: "he08", text: "Unutmak için değil, kırgınlığın yükünden kendimi özgür kılmak için affediyorum.", theme: "healing", relatedSign: "libra" },
  { id: "he09", text: "Yumuşaklıkta güç vardır. Kendime nazik olmaya izin veriyorum.", theme: "healing", relatedSign: "cancer" },
  { id: "he10", text: "Yavaş hissettirdiğinde bile iyileşme sürecimin bilgeliğine güveniyorum.", theme: "healing", relatedSign: "pisces" },
  { id: "he11", text: "Artık bana ait olmayanı bırakmanın getirdiği huzuru hak ediyorum.", theme: "healing" },
  { id: "he12", text: "Aldığım her nefes bir yenilenme eylemidir. Şimdiden iyileşiyorum.", theme: "healing" },
];
